### ISSUE TITLE
DED zip folder v1.15 does not include er_oled.h file

### ISSUE THREAD

**Issue by cosigin** [jg-storey/ded#1]
hi,

when i unzip the folder it opens without the file er_oled.h

can you please unzip the folder and see if that happens for you as well?

**Comment by RobinsonResearchInstitute** [comment]
Checked. Cannot replicate the problem. All files are present. 
![image](https://user-images.githubusercontent.com/61482118/171731721-5c3a241b-0ce0-442d-a983-0985000ddc32.png)

**Comment by jg-storey** [comment]
Checked. Cannot replicate problem. All files are present.
![image](https://user-images.githubusercontent.com/69622675/171731953-4885cc25-0754-4244-9397-eafa143469cb.png)
